name: batman actions
on: workflow_dispatch

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: batmanvapp
  EKS_CLUSTER: batman-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: Code checkout
        uses: actions/checkout@v4

      # Run Maven tests
      - name: Maven test
        run: mvn test

      # Run Maven Checkstyle
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Set up Java 11 for SonarScanner compatibility
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Supported distributions: temurin, zulu, etc.
          java-version: "11"

      # Set up SonarScanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run SonarScanner for code analysis
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

      # Check SonarQube Quality Gate status
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
