name: batman actions

on: workflow_dispatch

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: batmanvapp
  EKS_CLUSTER: batman-eks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (required for Java projects and SonarQube)
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      # Install Maven
      - name: Install Maven
        run: sudo apt-get install maven -y

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run tests (optional, if you want test coverage)
      - name: Run Tests
        run: mvn test

      # Download and install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip -O /tmp/sonar-scanner.zip
          unzip /tmp/sonar-scanner.zip -d /tmp
          mv /tmp/sonar-scanner-* /tmp/sonar-scanner
          rm /tmp/sonar-scanner.zip
          echo "/tmp/sonar-scanner/bin" >> $GITHUB_PATH

      # Run SonarQube Scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner -X \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes/

      ## Post build cleanup
      - name: Cleanup
        run: mvn clean
